image: node:18-alpine
stages:
  - build
  - deploy

build:
  image: node:18-alpine
  stage: build
  tags:
    - docker-runner
  script:
    - yarn install --immutable
    # - yarn verify --passWithNoTests
    - yarn build
release:
  image: node:18-alpine
  stage: deploy
  tags:
    - docker-runner
  script:
    - yarn install --immutable
    - yarn npm publish
