image: node:18-alpine
stages:
  - build
  - package-publish
  - trigger-distro-build

default:
  cache: &default_cache
    key: "Frontend-cache"
    paths:
      - node_modules/
      - .yarn/cache/
      - yarn.lock
      - dist/

build:
  image: node:18-alpine
  stage: build
  tags:
    - docker-runner
  script:
    - yarn config set -H enableImmutableInstalls false
    - yarn install
    - yarn up
    - yarn build
  cache:
    <<: *default_cache
package-publish:
  image: node:18-alpine
  stage: package-publish
  tags:
    - docker-runner
  script:
    - npm version --no-git-tag-version  $(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.$CI_PIPELINE_ID
    - yarn npm publish --tag next
  cache:
    <<: *default_cache
    policy: pull
trigger_job:
  stage: trigger-distro-build
  only:
    - main
  trigger:
    project: openmrs/openmrs-simc-distro-referenceapplication
