image: node:18-alpine
stages:
  - build
  - deploy

build:
  image: node:18-alpine
  stage: build
  tags:
    - k8srunner
  script:
    - npm install --global yarn
    - yarn install --immutable
    - yarn verify
    - yarn build
release:
  image: node:18-alpine
  stage: deploy
  tags:
    - k8srunner
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm install --global yarn
    - yarn install --immutable
    - yarn npm publish