image: node:18-alpine
stages:
  - build
  - pre-release

build:
  image: node:18-alpine
  stage: build
  tags:
    - docker-runner
  script:
    - yarn install --immutable
    # - yarn verify --passWithNoTests
    - yarn build
pre-release:
  image: node:18-alpine
  stage: pre-release
  tags:
    - docker-runner
  script:
    - npm install semver
    - npm version --no-git-tag-version  $(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.$CI_PIPELINE_ID
    - yarn install --immutable
    - yarn npm publish --tag next
